### ISSUE TITLE
Refine raw installation

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#486]
- [x] Suggest/require necessary plugins
- [ ] be able to install the theme on a fresh WordPress install and have it appear sensibly

**Comment by YuiZoldyck** [comment]
No need to suggest plugins.
Replace images in the resource folder and upload ones with BYU on it to solve the header issue.

**Comment by YuiZoldyck** [comment]
@WorldsEndless  No plugins are necessary for the installation of the theme. What went wrong is that the resource folder doesn't have images of BYU itself for the header. 
Looking over the CSS, everything is as it should be. The only issue I am unsure of is the blue background that covers the header.

**Comment by WorldsEndless** [comment]
Try making a dummy site for a different college (or a made-up one) and see if you have any installation troubles

**Comment by WorldsEndless** [comment]
We learned that ACF is necessary right now, since both People (directory) and blog posts (front page) draw on ACF data

**Comment by YuiZoldyck** [comment]
Made edits to the theme so that it looks like the odh one.
Is there anything else that I should look for? This is how it looks when I install with the theme. 
<img width="1440" alt="Screen Shot 2022-08-04 at 6 15 22 PM" src="https://user-images.githubusercontent.com/89797588/182976200-20725d90-85c0-46b7-954c-6969666beae3.png">

<img width="1440" alt="Screen Shot 2022-08-04 at 6 15 26 PM" src="https://user-images.githubusercontent.com/89797588/182976196-d91e9311-0aec-440c-a4cc-092000e68a3c.png">

**Comment by YuiZoldyck** [comment]
<img width="1440" alt="Screen Shot 2022-08-05 at 2 10 43 PM" src="https://user-images.githubusercontent.com/89797588/183155594-69e7fafb-09a4-41f5-8747-f92e832281c8.png">

<img width="1440" alt="Screen Shot 2022-08-05 at 2 10 32 PM" src="https://user-images.githubusercontent.com/89797588/183155633-4c5e2130-d002-4e72-93a5-960b748a2d31.png">

what theme looks like on posts and pages on raw installation of theme
