### ISSUE TITLE
Search issues: mobile menubar search button is too easily tapped

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#488]
Accidentally hitting the search button ends attempts to search, perhaps before they've begun. Which are the favorite solutions for a mobile-friendly search execution?

**Comment by YuiZoldyck** [comment]
What the current mobile UI looks like compared to byu.edu
![Screen Shot 2022-07-28 at 3 22 10 PM](https://user-images.githubusercontent.com/89797588/181647962-55baf6ad-4d66-4319-8752-5566bce97afd.png)


This is the first option where the search bar itself is elongated so that it is not as easy to hit it on accident. Done through CSS only.

![Screen Shot 2022-07-28 at 4 28 55 PM](https://user-images.githubusercontent.com/89797588/181647915-f521172c-6e1c-48f7-9d08-1a1413d78517.png)
