### ISSUE TITLE
Bug: mobile menu is messed up

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#502]
Related to #500, but there still appear to be issues on staging. Mobile menu is spitting out raw info on pages before getting to its normal output

![image](https://user-images.githubusercontent.com/5042778/182444531-09d8a4e0-8aac-4b91-9ade-2f99b70d7ef8.png)

**Comment by julianayue** [comment]
I've implementing the change on humstaging. Created a new "Top-navigation menu" on Appearance --> Menu and fixed the menu issue. I think this menu was deleted by accident which was why it was causing the issue because my local host (no issue) had this menu but not humstaging.
![Screen Shot 2022-07-28 at 11 03 49](https://user-images.githubusercontent.com/71421187/182679561-8a26193f-d5b0-4488-bec5-4864392722cb.png)
<img width="1440" alt="Screen Shot 2022-08-03 at 12 10 13" src="https://user-images.githubusercontent.com/71421187/182679566-b880e380-b5b5-4b99-b925-6cb80f55633d.png">

**Comment by julianayue** [comment]
@WorldsEndless What are your thoughts?

**Comment by WorldsEndless** [comment]
looks good!
