### ISSUE TITLE
Add hidden ACF Project Status field

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#516]
Create a hidden field for projects that contains the overall status of the project, as calculated by #504 , but is "read only" by being hidden from users and only accessible by code. It should automatically update with any changes to intake, live, or archived date.

https://www.advancedcustomfields.com/resources/update_field/

https://www.advancedcustomfields.com/resources/custom-location-rules/

**Comment by WorldsEndless** [comment]
The contract on this function should be like, `function get-project-status ($post_id){}` returns a string  that can be used for the classname "live" on one of the others

**Comment by YuiZoldyck** [comment]
Rather than ACFs, I created a field in Pods that will store the project_status and it will automatically update when ever you update/create the project.

<img width="1440" alt="Screen Shot 2022-08-22 at 5 59 10 PM" src="https://user-images.githubusercontent.com/89797588/186040166-39c8f5a0-2bf8-4bd5-bf40-4cc1d5122cb2.png">

![Screen Shot 2022-08-22 at 6 01 33 PM](https://user-images.githubusercontent.com/89797588/186040247-c2e0f63b-88df-4d02-8b5d-3da56265a6de.png)
