### ISSUE TITLE
Remove left-border on the nav bar

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/wp-humanities-byu#520]
![image](https://user-images.githubusercontent.com/5042778/184977053-e513acc9-e35f-4d12-96e4-5da82b2acb14.png)

**Comment by spencercheng** [comment]
![image](https://user-images.githubusercontent.com/89827794/185443133-cefc8615-dbea-4df5-81b5-8cdbd72e7c20.png)
This is due to having two divs that have the same class. What's weird is on my Localhost it doesn't appear that way. This is what my Localhost has :
![image](https://user-images.githubusercontent.com/89827794/185443332-879418e6-b43f-4066-bc2d-8c2515142a11.png)
And it doesn't cause the issue.

**Comment by spencercheng** [comment]
One way to solve it is to use the `clip-path` style to make the left not have any box shadow, but it looks alittle bit weird. This is what it looks like on Humstaging: 
![image](https://user-images.githubusercontent.com/89827794/185444065-a967baf4-9e9d-4512-bada-9ee7390021ef.png)
