### ISSUE TITLE
`<ul>` elements have different sized and weighted fonts

### ISSUE THREAD

**Issue by briancroxall** [BYU-ODH/wp-humanities-byu#567]
![2023-02-07_15-32-44](https://user-images.githubusercontent.com/1005115/217381848-933f1dab-4988-4641-adc9-e6d4893ba645.png)

**Comment by spencercheng** [comment]
@briancroxall  Where can I find this page?

**Comment by briancroxall** [comment]
https://odh.byu.edu/project-proposal-process/

**Comment by spencercheng** [comment]
The Issue seems to be with the styling of the <ul> tag. It had a font weight of 600. I recreated the post on humstaging and commented out the styles and this is what it looks like: 
![image](https://user-images.githubusercontent.com/89827794/223187935-3994f67d-9aad-4f13-a8f5-3f1033cc8d47.png)
(Disregard the messed-up indents)
